
FROM eclipse-temurin:17-jdk
WORKDIR /app
COPY . .
RUN chmod +x mvnw && ./mvnw clean package -DskipTests

# Exponer el puerto (Render usa la variable PORT o por defecto 8080)
EXPOSE 8080

# Usar solo UN comando CMD - ejecutar el JAR compilado
CMD ["java", "-jar", "target/config-server-0.0.1-SNAPSHOT.jar"]