spring:
  application:
    name: servicio-ventas

  data:
    mongodb:
      host: localhost
      port: 27017
      database: tortasSallela

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

    
  config:
    import: optional:configserver:http://localhost:8888