spring:
  application:
    name: usuarios
  data:
    mongodb:
      uri: mongodb+srv://cristicn2004:78357Cas123%2B@clustertortas0.nazanhp.mongodb.net/tortasSallela?retryWrites=true&w=majority&ssl=true


    
  config:
    import: optional:configserver:https://tortas-mejorado.onrender.com