spring:
  application:
    name: servicio-ordenes
  data:
    mongodb:
      uri: mongodb+srv://cristicn2004:78357Cas123+@clustertortas0.nazanhp.mongodb.net/tortasSallela

    
  config:
    import: optional:configserver:http://localhost:8888