spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/cristicn2024/tortas-config
          default-label: re-do2
          clone-on-start: true
